### PR TITLE
fix: corrected input port to get-port

### LINKED ISSUE #164: new get-port version breaks
When setting env var PORT="8080"

New version of getPort requires an integer instead of a string. So when opts.port as an env var the value does not get converted to an integer and get-port gives you a different port.

The way to correct this would be to convert the process.env PORT value to integer.

### LINKED ISSUE #168: Port is taken, but it's not!
```
sirv-cli: 3.0.0
```

image

Check port
```
❯ nc -zv localhost 1-5100 2>&1 | grep succeeded
Connection to localhost port 22 [tcp/ssh] succeeded!
Connection to localhost port 5000 [tcp/commplex-main] succeeded!
```

or

```
lsof -i -P -n | grep 5001
```

---

```
sirv-cli: 2.0.2
```

image

Check port
```
❯ lsof -i -P -n | grep 5001
node      13086 takamoto   18u  IPv4 0xb21424e14870c1f5      0t0  TCP 127.0.0.1:5001 (LISTEN)
```

### PR DESCRIPTION
**Pull request by pixeldrew**
Corrected input to get-port so that it takes an integer and validation is correct on line 84. fixes #164

---

Also closes #168

### CODE REVIEW

File: packages/sirv-cli/index.js [hunk 1]
```diff
@@ -78,7 +78,7 @@ module.exports = function (dir, opts) {
 		});
 	}
 
-	opts.port = PORT || opts.port;
+	opts.port = parseInt(PORT || opts.port, 10);
```
Comment (lukeed) [inline packages/sirv-cli/index.js:81]:
```suggestion
	opts.port = +(PORT || opts.port);
```

**Comment by lukeed** [comment]
Thank you
