### PR TITLE
fix(sirv): avoid false-positive on too big range end

### LINKED ISSUE #140: Range request overlap is handled incorrectly
[RFC 7233, Section 4.4](https://datatracker.ietf.org/doc/html/rfc7233#section-4.4): 

> The 416 (Range Not Satisfiable) status code indicates that none of
> the ranges in the request's Range header field ([Section 3.1](https://datatracker.ietf.org/doc/html/rfc7233#section-3.1)) **overlap**
> the current extent of the selected resource

> For byte ranges, failing to overlap the current extent means that the
> **first-byte-pos** of all of the byte-range-spec values were greater than
> the current length of the selected representation.

Current implementation limits `end` of range and returns `416` error:
https://github.com/lukeed/sirv/blob/886cc962a345780cd78f8910cdcf218db2a8d955/packages/sirv/index.js#L72-L80

`end` can be limited with `Math.min`, for example, and excluded from condition

```JavaScript
let [x, y] = req.headers.range.replace('bytes=', '').split('-');
let end = opts.end = Math.min(parseInt(y, 10) || stats.size - 1, stats.size - 1);
let start = opts.start = parseInt(x, 10) || 0;

if (start >= stats.size) {
	res.setHeader('Content-Range', `bytes */${stats.size}`);
	res.statusCode = 416;
	return res.end();
}
```

### PR DESCRIPTION
**Pull request by dmkret**
Closes #140

### CODE REVIEW

File: tests/sirv.js [hunk 1]
```diff
@@ -1032,6 +1032,21 @@ ranges('should throw `416` when range cannot be met (overflow)', async () => {
 	}
 });
 
+ranges('should shrink range end is it cannot be met (overflow)', async () => {
```
Comment (benmccann) [inline tests/sirv.js:1035]: I'm guessing you meant "if" here?
```suggestion
ranges('should shrink range end if it cannot be met (overflow)', async () => {
```

**Comment by benmccann** [comment]
@dmkret I don't have merge rights on this repo

**Comment by lukeed** [comment]
Sorry I’m in the middle of a move. Will look tomorrow or Monday
